#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_DIR="$ROOT_DIR/core"
CORE_BUILD_DIR="$CORE_DIR/build"
CORE_INSTALL_DIR="$CORE_BUILD_DIR/install"
POLICY_TOOLCHAIN_FILE="$ROOT_DIR/cmake/policy_toolchain.cmake"

rm -rf "$CORE_BUILD_DIR" "$CORE_DIR/install"
mkdir -p "$CORE_BUILD_DIR"
pushd "$CORE_BUILD_DIR" >/dev/null

cmake -DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX="$CORE_INSTALL_DIR" \
	-DTRITON_CORE_HEADERS_ONLY=OFF \
	-DTRITON_ENABLE_GPU=ON \
	-DTRITON_ENABLE_S3=ON \
	-DTRITON_ENABLE_MALI_GPU=OFF \
	-DTRITON_ENABLE_STATS=OFF \
	-DTRITON_ENABLE_METRICS=OFF \
	-DTRITON_ENABLE_METRICS_GPU=OFF \
	-DTRITON_ENABLE_METRICS_CPU=OFF \
	-DTRITON_ENABLE_TRACING=OFF \
	-DTRITON_ENABLE_NVTX=OFF \
	-DTRITON_ENABLE_ENSEMBLE=OFF \
	-DTRITON_ENABLE_GCS=OFF \
	-DTRITON_ENABLE_AZURE_STORAGE=OFF \
	-DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized ${CMAKE_CXX_FLAGS:-}" \
	-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DCMAKE_TOOLCHAIN_FILE="$POLICY_TOOLCHAIN_FILE" ..

cmake --build . --target install -j"$(nproc)"

popd >/dev/null

export LIBRARY_PATH="$CORE_INSTALL_DIR/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
export LD_LIBRARY_PATH="$CORE_INSTALL_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

pushd "$ROOT_DIR" >/dev/null
cargo test
popd >/dev/null